config/routes.rb
Rails.application.routes.draw do

  namespace :accounts do
    get 'search', to: 'search#account_extract'
  end

  namespace :accounts do
    resources :accounts, only: %i[index new edit create update show]
    get 'balance_account', to: 'accounts#balance_account'
    resources :profile_users, only: %i[edit update]
    resources :withdrawals, only: %i[new create show]
    resources :transfers, only: %i[new create show]
  end

  resources :deposits, only: %i[new create show]

  devise_for :users

  root 'home#index'
end

app/views/layouts/shared/_footer.html.erb
<!-- /.container -->

 <div class="container">

     <hr>

     <!-- Footer -->
     <footer>
         <div class="row">
             <div class="col-lg-12">
                 <p>Copyright &copy; <%= 'Virtual Banking' %> <%= Date.today.year %></p>
             </div>
         </div>
     </footer>

 </div>
 <!-- /.container -->

app/views/layouts/shared/_navigation.html.erb
     <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <%= link_to 'Virtual Banking', root_path, class: "navbar-brand" %>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav pull-right">
                  <% unless user_signed_in? %>
                    <li>
                        <%= link_to "Login", new_user_session_path %>
                    </li>
                    <li>
                         <%= link_to "Cadastrar-se", new_user_registration_path %>
                    </li>
                  <% else %>
                    <li>
                        <%= link_to current_user.email, "#" %>
                    <li>
                      <% if current_user.account.present? %>
                        <%= link_to "Conta", accounts_search_path,  data: { no_turbolink: true } %>
                      <% end %>
                    </li>
                    <li>
                        <%= link_to "Sair", destroy_user_session_path, method: :delete %>
                    </li>
                  <% end %>
                  <li>
                      <%= link_to "Cadastrar Conta", new_accounts_account_path %>
                  </li>
                </ul>
            </div>
        </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

app/views/layouts/shared/_notification.html.erb
<% if notice %>
  <%= javascript_tag "$.notify({ message: '#{notice}', icon: 'glyphicon glyphicon-ok-circle' },
                               { type: 'success', placement: { from: 'top', align: 'center'},
                                 delay: 400});" %>
<% end %>

<% if alert %>
  <%= javascript_tag "$.notify({ message: '#{alert}', icon: 'glyphicon glyphicon-remove-circle' },
                               { type: 'danger', placement: { from: 'top', align: 'center'},
                                 delay: 400});" %>
<% end %>